export const languageEmojis: Record<string, string> = {
  'en': '🇬🇧', // English
  'nl': '🇳🇱', // Dutch
  'fr': '🇫🇷', // French
  'de': '🇩🇪', // German
  'es': '🇪🇸', // Spanish
  'it': '🇮🇹', // Italian
  'pt': '🇵🇹', // Portuguese
  'ru': '🇷🇺', // Russian
  'zh': '🇨🇳', // Chinese
  'ja': '🇯🇵', // Japanese
  'ko': '🇰🇷', // Korean
  'ar': '🇸🇦', // Arabic
  'hi': '🇮🇳', // Hindi
  'tr': '🇹🇷', // Turkish
  'pl': '🇵🇱', // Polish
  'sv': '🇸🇪', // Swedish
  'no': '🇳🇴', // Norwegian
  'da': '🇩🇰', // Danish
  'fi': '🇫🇮', // Finnish
  'el': '🇬🇷', // Greek
  'he': '🇮🇱', // Hebrew
  'th': '🇹🇭', // Thai
  'vi': '🇻🇳', // Vietnamese
  'id': '🇮🇩', // Indonesian
  'ms': '🇲🇾', // Malay
  'uk': '🇺🇦', // Ukrainian
  'cs': '🇨🇿', // Czech
  'hu': '🇭🇺', // Hungarian
  'ro': '🇷🇴', // Romanian
  'bg': '🇧🇬', // Bulgarian
  'hr': '🇭🇷', // Croatian
  'sr': '🇷🇸', // Serbian
  'sk': '🇸🇰', // Slovak
  'sl': '🇸🇮', // Slovenian
  'lt': '🇱🇹', // Lithuanian
  'lv': '🇱🇻', // Latvian
  'et': '🇪🇪', // Estonian
  'sq': '🇦🇱', // Albanian
  'mk': '🇲🇰', // Macedonian
  'mt': '🇲🇹', // Maltese
  'is': '🇮🇸', // Icelandic
  'ga': '🇮🇪', // Irish
  'cy': '🏴󐁧󐁢󐁷󐁬󐁳󐁿', // Welsh
  'eu': '🏴', // Basque
  'ca': '🏴', // Catalan
  'gl': '🏴', // Galician
  'fa': '🇮🇷', // Persian
  'ur': '🇵🇰', // Urdu
  'bn': '🇧🇩', // Bengali
  'pa': '🇮🇳', // Punjabi
  'gu': '🇮🇳', // Gujarati
  'ta': '🇮🇳', // Tamil
  'te': '🇮🇳', // Telugu
  'kn': '🇮🇳', // Kannada
  'ml': '🇮🇳', // Malayalam
  'si': '🇱🇰', // Sinhala
  'my': '🇲🇲', // Burmese
  'km': '🇰🇭', // Khmer
  'lo': '🇱🇦', // Lao
  'ka': '🇬🇪', // Georgian
  'hy': '🇦🇲', // Armenian
  'az': '🇦🇿', // Azerbaijani
  'kk': '🇰🇿', // Kazakh
  'ky': '🇰🇬', // Kyrgyz
  'uz': '🇺🇿', // Uzbek
  'tg': '🇹🇯', // Tajik
  'tk': '🇹🇲', // Turkmen
  'mn': '🇲🇳', // Mongolian
  'ne': '🇳🇵', // Nepali
  'sw': '🇰🇪', // Swahili
  'am': '🇪🇹', // Amharic
  'ha': '🇳🇬', // Hausa
  'yo': '🇳🇬', // Yoruba
  'ig': '🇳🇬', // Igbo
  'zu': '🇿🇦', // Zulu
  'xh': '🇿🇦', // Xhosa
  'af': '🇿🇦', // Afrikaans
  'fil': '🇵🇭', // Filipino
  'jv': '🇮🇩', // Javanese
  'su': '🇮🇩', // Sundanese
  'tl': '🇵🇭', // Tagalog
  'mg': '🇲🇬', // Malagasy
  'so': '🇸🇴', // Somali
  'ti': '🇪🇷', // Tigrinya
  'other': '🌐'  // Other/Unknown
};

export function getLanguageEmoji(languageCode: string): string {
  return languageEmojis[languageCode] || languageEmojis['other'];
}